### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/SVASSS#1]
The app works at commit 33f6e38 but not downstream at 8b338756 or e52ecbf (the master)

I suspect it is something in the fix_encoding stuff you are doing. When you use `enc2utf8()` or `enc2native()` the function behaviour depends on the native encoding of the system and the encoding of the source object being correctly specified. This could result in something that works on your system (native latin-1) but breaks on a system that is native UTF-8.

I think you should revert to the state at 33f6e38 and definitively determine the encoding of the source data from the database. Then examine each step in the manipulation of that to ensure it has declared encoding. You should not have to remove åöäÅÖÄ from any dataset.

If you use äåöÄÖÅ in the **code** anywhere, a portable way of specifying that is to use the following replacements:

Ä --> /u00C4
Å --> /u00C5
Ö --> /u00D6
ä --> /u00E4
ö --> /u00F6
å --> /u00E5

however, you want to call a column in a data.frame like this:
```
df[,"column_name"]
```

not like this:

```
df$column_name
```

**Comment by nandadorea** [comment]
Issue solved with declaring the encoding as "Latin1" before saving the data. For column names the swedish characters are still forcefully removed...
